/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifContactRouteImport } from './routes/tarif-contact'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RendezVousRouteImport } from './routes/rendez-vous'
import { Route as PourQuiRouteImport } from './routes/pour-qui'
import { Route as IndexRouteImport } from './routes/index'

const TarifContactRoute = TarifContactRouteImport.update({
  id: '/tarif-contact',
  path: '/tarif-contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RendezVousRoute = RendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => rootRouteImport,
} as any)
const PourQuiRoute = PourQuiRouteImport.update({
  id: '/pour-qui',
  path: '/pour-qui',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pour-qui': typeof PourQuiRoute
  '/rendez-vous': typeof RendezVousRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarif-contact': typeof TarifContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pour-qui': typeof PourQuiRoute
  '/rendez-vous': typeof RendezVousRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarif-contact': typeof TarifContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pour-qui': typeof PourQuiRoute
  '/rendez-vous': typeof RendezVousRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarif-contact': typeof TarifContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pour-qui'
    | '/rendez-vous'
    | '/sitemap.xml'
    | '/tarif-contact'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pour-qui' | '/rendez-vous' | '/sitemap.xml' | '/tarif-contact'
  id:
    | '__root__'
    | '/'
    | '/pour-qui'
    | '/rendez-vous'
    | '/sitemap.xml'
    | '/tarif-contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PourQuiRoute: typeof PourQuiRoute
  RendezVousRoute: typeof RendezVousRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TarifContactRoute: typeof TarifContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarif-contact': {
      id: '/tarif-contact'
      path: '/tarif-contact'
      fullPath: '/tarif-contact'
      preLoaderRoute: typeof TarifContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rendez-vous': {
      id: '/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/rendez-vous'
      preLoaderRoute: typeof RendezVousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pour-qui': {
      id: '/pour-qui'
      path: '/pour-qui'
      fullPath: '/pour-qui'
      preLoaderRoute: typeof PourQuiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PourQuiRoute: PourQuiRoute,
  RendezVousRoute: RendezVousRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TarifContactRoute: TarifContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
